/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDonationsRouteImport } from './routes/api/public/donations'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDonationsRoute = ApiPublicDonationsRouteImport.update({
  id: '/api/public/donations',
  path: '/api/public/donations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campanhas': typeof CampanhasRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/sobre': typeof SobreRoute
  '/api/public/donations': typeof ApiPublicDonationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campanhas': typeof CampanhasRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/sobre': typeof SobreRoute
  '/api/public/donations': typeof ApiPublicDonationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campanhas': typeof CampanhasRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/sobre': typeof SobreRoute
  '/api/public/donations': typeof ApiPublicDonationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campanhas'
    | '/contato'
    | '/equipe'
    | '/sobre'
    | '/api/public/donations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campanhas'
    | '/contato'
    | '/equipe'
    | '/sobre'
    | '/api/public/donations'
  id:
    | '__root__'
    | '/'
    | '/campanhas'
    | '/contato'
    | '/equipe'
    | '/sobre'
    | '/api/public/donations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampanhasRoute: typeof CampanhasRoute
  ContatoRoute: typeof ContatoRoute
  EquipeRoute: typeof EquipeRoute
  SobreRoute: typeof SobreRoute
  ApiPublicDonationsRoute: typeof ApiPublicDonationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/donations': {
      id: '/api/public/donations'
      path: '/api/public/donations'
      fullPath: '/api/public/donations'
      preLoaderRoute: typeof ApiPublicDonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampanhasRoute: CampanhasRoute,
  ContatoRoute: ContatoRoute,
  EquipeRoute: EquipeRoute,
  SobreRoute: SobreRoute,
  ApiPublicDonationsRoute: ApiPublicDonationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}